### PR TITLE
added dark theme

### PR DESCRIPTION
**Pull request by jitendravjh**
Follow-up to https://github.com/TuringLang/turinglang.github.io/pull/92

### CODE REVIEW

**Comment by shravanngoswamii** [comment]
Hello @penelopeysm, version check workflow is failing here, can you please have a look at it?

**Comment by penelopeysm** [comment]
@shravanngoswamii I'm fairly sure it's because the PR is being made from a fork, it runs fine on #510.

Will edit the action to handle this case more gracefully!

**Comment by shravanngoswamii** [comment]
> Will edit the action to handle this case more gracefully, but it's safe to ignore it for now!

Thank You, @penelopeysm!

**Comment by shravanngoswamii** [comment]
@jitendravjh I think the background colour of this breadcrumb should be same as main bg-color!
image

**Comment by jitendravjh** [comment]
Thank you for the feedback! I'll update the breadcrumb background color.

**Review by penelopeysm — APPROVED** [review]

**Review by shravanngoswamii — APPROVED** [review]

**Pull request merged**
