### PR TITLE
Re-enable numerical asserts since CI now uses Quarto 1.6

### LINKED ISSUE #533: Random assertions can fail randomly (despite seeding)
e.g. this block in the VI tutorial:

https://github.com/TuringLang/docs/blob/b53df242783c1b14437c9468bd7f3914ec69241a/tutorials/09-variational-inference/index.qmd#L154-L162

Somehow, these assertions failed in one CI run: https://github.com/TuringLang/docs/actions/runs/11281015562/job/31375300973

Here's another failure of the same code block: https://github.com/TuringLang/docs/actions/runs/11281201489/job/31376048754

Here's the Gaussian mixture model tutorial failing: https://github.com/TuringLang/docs/actions/runs/11283217753/job/31382221263

Not sure how this happened as the random seed was already set at the top of the file. It seems that some function isn't respecting it.

### PR DESCRIPTION
**Pull request by penelopeysm**
The docs contain some assertions to make sure that e.g. posterior predictions are numerically accurate. Due to #533 these assertions were sometimes randomly failing, and I had to comment them out to avoid spurious CI failures.

Since the upstream issue has been fixed, and a new version of Quarto that contains this bugfix released, this PR re-enables the assertions.

Closes #533.

### CODE REVIEW

**Comment by penelopeysm** [comment]
Actually the upstream issue is not fully fixed; there is a new version of QuartoNotebookRunner.jl with the fix (0.11.5) but Quarto itself needs to be updated https://github.com/quarto-dev/quarto-cli/blob/cf81582a26c4e43501f21ae5dec4d8be90acd4e3/src/resources/julia/Project.toml#L2

**Comment by penelopeysm** [comment]
PR submitted to Quarto. https://github.com/quarto-dev/quarto-cli/pull/11100

**Comment by penelopeysm** [comment]
I have to say, it's very frustrating when the CI runner uses the version of the workflow on the target branch rather than the version of the workflow that I literally changed in this PR.

**Review by mhauru — APPROVED** [review]
Good stuff

**Pull request merged**
