### PR TITLE
Move MCMC `Interface Guide` into inference section. 

### PR DESCRIPTION
**Pull request by yebai**

### CODE REVIEW

**Comment by torfjelde** [comment]
Tbh, should we not just remove this? It's completely outdated and we now have a better version for how to implement samplers

**Comment by torfjelde** [comment]
#468

**Comment by torfjelde** [comment]
https://github.com/TuringLang/docs/issues/477 and https://github.com/TuringLang/Turing.jl/issues/2272 seem related

**Comment by penelopeysm** [comment]
Closing as this was also done as part of #520

**Pull request closed without merging**
